name: personality_score
description: A new Flutter project.
publish_to: 'none'

version: 1.0.10

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  responsive_builder: ^0.4.1
  flutter_svg: ^1.1.0+1
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20
  json_annotation: ^4.3.0
  provider: ^6.1.2
  share_plus: ^9.0.0
  cupertino_icons: ^1.0.8
  lottie: ^3.1.2
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  firebase_storage: ^12.1.0
  video_player: ^2.5.1
  mailer: ^5.0.0
  youtube_player_iframe: ^2.2.0 # Check for the latest version on pub.dev
  flutter_rating_bar: ^4.0.0
  package_info_plus: ^4.0.0
  universal_html: ^2.0.8
  path_provider: ^2.0.15
  flutter_email_sender: ^5.0.2
  pdf: ^3.8.1
  http: ^1.2.1
  intl: ^0.17.0
  printing: ^5.9.0
  syncfusion_flutter_pdf: ^20.4.39
  flutter_pdfview: ^1.3.4
  pdf_merger: ^0.0.6
  cached_network_image: ^3.2.3 # Optional for caching images
  dio: ^5.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  json_serializable: ^6.1.5
  flutter_lints: ^4.0.0
  mockito: ^5.0.16
  flutter_email_sender: ^5.0.2

  firebase_auth_mocks: ^0.14.0
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/auswertungen/
    - assets/icons/

  fonts:
    - family: SortsMillGoudy
      fonts:
        - asset: assets/fonts/SortsMillGoudy-Italic.ttf

    - family: AlexBrush
      fonts:
        - asset: assets/fonts/AlexBrush-Regular.ttf