name: personality_score
description: A new Flutter project.
publish_to: 'none'

version: 1.0.10

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  responsive_builder: ^0.4.1
  flutter_svg: ^1.1.0+1
  flutter:
    sdk: flutter
  url_launcher: ^6.0.20
  json_annotation: ^4.3.0
  provider: ^6.1.2
  share_plus: ^9.0.0
  cupertino_icons: ^1.0.8
  lottie: ^3.1.2
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  cloud_firestore: ^5.0.2
  mailer: ^5.0.0
  youtube_player_iframe: ^2.2.0 # Check for the latest version on pub.dev
  flutter_rating_bar: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  json_serializable: ^6.1.5
  flutter_lints: ^4.0.0
  mockito: ^5.0.16

  firebase_auth_mocks: ^0.14.0
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/auswertungen/
    - assets/icons/