// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYoub2zhvn4ZFjHMKnriDGRBFoLsXFM_Q',
    appId: '1:580383824204:web:6c030b86591bb5db2357e9',
    messagingSenderId: '580383824204',
    projectId: 'personality-score',
    authDomain: 'personality-score.firebaseapp.com',
    storageBucket: 'personality-score.appspot.com',
    measurementId: 'G-PZ67801578',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAzd1ntGLGCxnnw_DjraVgELChwCevdcM',
    appId: '1:580383824204:android:586078a47d93e2cb2357e9',
    messagingSenderId: '580383824204',
    projectId: 'personality-score',
    storageBucket: 'personality-score.appspot.com',
  );

}